### ISSUE TITLE
GBS to ALLMAPS

### ISSUE THREAD

**Issue by mictadlo** [tanghaibao/jcvi#114]
Hi,
We used ALLHIC to create chromosome groups. We have one population consisted of 192 F3 lines resulting from a cross between two plants.

Do anyone know how the GBS data could be used to improve ALLHiC results with help of ALLMAPS? 

Thank you in advance,

Michal

**Comment by tanghaibao** [comment]
@mictadlo 

ALLHiC only processes HiC data. If you have GBS map, the best starting point is ALLMAPS so that scaffolds may be pieced together assuming collinearity.

Haibao

**Comment by hrpelg** [comment]
I am using your software to anchor a genetic map done from GBS, to an assembly. I got the pseudomolecules with ALLMAPs and after I used Nucmer to compare my assembly (wild species) to a its reference genome (domesticated species) and I got the diagonal but some scaffolds within each pseudomolecule are translocated. Should I flip those? So my questions is would you trust more teh genetic map or the synteny with the ref genome? If I need to flip them, do you know any tool?

I flipped them just to check, changing the orientation (+/-) in the agp file and re running the path options with the same original bed.file. So I got a perfect diagonal between my assembly and the reference..but then the figure ALLMAPS produced linking the genetic map with the scaffolds won't be representing what I finally did to get all the scaffolds in the pseudomolecule oriented. Any suggestions?

thanks a lot for the software and in advance for any advice

**Comment by mictadlo** [comment]
@hrpelg : Could you please share with me how you analyzed your GBS data?

**Comment by tanghaibao** [comment]
@hrpelg 
Sure - I am not sure that I fully understand the question though. ALLMAPS are showing the same set of data on the left panel (links between chromosome and genetic map) and right panel (dot plots). So if some scaffolds need to be flipped, it's showing up on both sides. Is this what you were asking? 

Per your previous question, I'd trust genetic maps more since it is more or less from the same species. Depending on the distance between your organism to the ref genome, synteny might not always be perfect.

Haibao

**Comment by hrpelg** [comment]
Thank you @tanghaibao ! Okay, so the plots just show the conflicts. I though they were already showing the scaffolds in the right orientation that is shown in agp. 

How can I get thinner lines in the plots? I have too many markers and I can not see properly the links

Thanks a lot
