### ISSUE TITLE
AMBIGUOUS scaffolds

### ISSUE THREAD

**Issue by francicco** [tanghaibao/jcvi#138]
Hi,

I'm scaffolding an assembly using a linkage map. By doing that AllMaps finds some ambiguities:

```
AMBIGUOUS Scf0000245 {('EisaPacBio-3',): 1, ('EisaPacBio-31',): 2, ('EisaPacBio-11',): 2}
AMBIGUOUS Scf0000271 {('EisaPacBio-10',): 2, ('EisaPacBio-9',): 3, ('EisaPacBio-6',): 3, ('EisaPacBio-4',): 3}
AMBIGUOUS Scf0000329 {('EisaPacBio-4',): 1, ('EisaPacBio-9',): 1, ('EisaPacBio-3',): 1, ('EisaPacBio-23',): 1}
AMBIGUOUS Scf0000352 {('EisaPacBio-5',): 1, ('EisaPacBio-28',): 1, ('EisaPacBio-23',): 1, ('EisaPacBio-20',): 1, ('EisaPacBio-12',): 1, ('EisaPacBio-27',): 1, ('EisaPacBio-7',): 1}
AMBIGUOUS Scf0000360 {('EisaPacBio-24',): 2, ('EisaPacBio-13',): 2}
AMBIGUOUS Scf0000387 {('EisaPacBio-15',): 1, ('EisaPacBio-3',): 1}
AMBIGUOUS Scf0000389 {('EisaPacBio-6',): 1, ('EisaPacBio-17',): 1, ('EisaPacBio-31',): 1}
AMBIGUOUS Scf0000423 {('EisaPacBio-1',): 1, ('EisaPacBio-14',): 1}
AMBIGUOUS Scf0000478 {('EisaPacBio-22',): 4, ('EisaPacBio-14',): 4}
```

How can I fix these?

Thanks
F

**Comment by tanghaibao** [comment]
@francicco 

These are the scaffolds that can be equally placed onto different linkage groups / chromosomes. For example, the last row says:

```
AMBIGUOUS Scf0000478 {('EisaPacBio-22',): 4, ('EisaPacBio-14',): 4}
```

Basically says `Scf0000478` have 4 markers anchorable to `EisaPacBio-22` and 4 markers anchorable to `EisaPacBio-14`. Since these are about similar,  ALLMAPS cannot decide which one to place the scaffold in.

Normally you don't need to do anything, and these will be called "unplaced contigs" and just fail to be confidently anchored.

Haibao
