### ISSUE TITLE
mcscan karyogram is count-based rather than coordinate-based

### ISSUE THREAD

**Issue by mitros** [tanghaibao/jcvi#170]
Is there any way to make the mcscan karyogram drawing coordinate based rather than count (generank) based? Perhaps I am missing it in the command line arguments.

**Comment by tanghaibao** [comment]
@mitros 

Yes, it is possible but the process is a bit manual. This is what I did when I was working on the figure below. Notice how you can control the `xstart` and `xend`. In the configuration file, you have something like this:

```
# y, xstart, xend, rotation, color, label, va,  bed
 .6,     .1,    .8,       0,      , Grape, top, grape.bed
 .4,     .1,    .8,       0,      , Peach, top, peach.bed
# edges
e, 0, 1, grape.peach.anchors.simple
```
If you know, for example, Grape is twice the size of Peach, then you can set Peach `xend` to  0.45 (0.1 + 0.7 / 2) so that would roughly approximate the genome size difference. This is a gross approximation since there are also gaps between chromosomes in order for the math to be accurate, but you get the idea.

Now the positions where the synteny blocks are coming out are still generank-based rather than coordinates. Unfortunately, this is currently not supported given how the plots are done currently.

[Source](https://science.sciencemag.org/content/345/6199/950)
![image](https://user-images.githubusercontent.com/106987/67349233-2f0fa080-f4fc-11e9-8413-34a049113bbe.png)

**Comment by tanghaibao** [comment]
@mitros 

While the relative genome sizes still need to be manually calculated as above, I have included an option `--basepair` so that the karyogram can be based on relative base pair positions rather than gene rank (default). For example, you can do:

    $ python -m jcvi.graphics.karyotype seqids layout --basepair

Sorry to have this done so late.

Haibao
