### ISSUE TITLE
replace connected curves with straight lines

### ISSUE THREAD

**Issue by LHXqwq** [tanghaibao/jcvi#185]
Is there any to replace connected curves with straight lines for the karyotype .pdf results, the curves looks very nice, but i am trying seveal genomes, the curves make pictures look confusing.Thanks ,best wishes.

**Comment by tanghaibao** [comment]
@LHXqwq 

Straight lines are not available at the moment -- although probably not too difficult to implement. I'll leave this issue open until I find the time to work on this but not likely going to happen soon. 

In the mean time, if you find a way to do this, please open a PR.

Haibao

**Comment by tanghaibao** [comment]
@LHXqwq 

I just implemented this change. To use, pull the latest change, so that we can have alternative shade style with option `--shadestyle`:

    $ python -m jcvi.graphics.karyotype seqids layout --shadestyle=line

Note that the shade now turns into lines instead of the Bezier curve before.

![Grape-peach-karyotype-line](https://www.dropbox.com/s/vvql9yd4k6ihzjt/grape.peach.karyotype-line.png?raw=1)

Please note that similar option is also available in `jcvi.graphics.synteny`. For example with:

    $ python -m jcvi.graphics.synteny blocks grape_peach.bed blocks.layout --shadestyle=line

![Grape-peach-blocks-line](https://www.dropbox.com/s/sheaenqyhkd5bbv/Grape-peach-blocks-line.png?raw=1)

Let me know if this works for you.

Haibao

**Comment by LHXqwq** [comment]
Thank you very much for your help. I updated the latest version of the software and can draw straight lines. For comparison of the genomes of multiple species, the straight lines do look clearer. Thank you again and wish you a happy life and a smooth work.
![图片](https://user-images.githubusercontent.com/50397597/70517473-9bf5fd00-1b73-11ea-9c99-21c213d33523.png)
![图片](https://user-images.githubusercontent.com/50397597/70517519-a912ec00-1b73-11ea-9817-e65c3eb5bc05.png)
