### ISSUE TITLE
python3 -m jcvi.graphics.karyotype seqids layout error

### ISSUE THREAD

**Issue by fantasticair** [tanghaibao/jcvi#199]
Hello,
I run `python3 -m jcvi.graphics.karyotype seqids layout`, get this error:
ValueError: Invalid number for map type 'Qualitative' and name 'Set2'.

**Comment by fantasticair** [comment]
ValueError: Invalid number for map type 'Qualitative' and name 'Set2'.
Valid numbers are : [3, 4, 5, 6, 7, 8]

**Comment by tanghaibao** [comment]
@fantasticair 

Are you using the latest version (v1.0.1)? Look for the last line when you execute:

```bash
python -m jcvi.graphics
```

This error occurred when you have >8 tracks, but should have been fixed in the latest version. If you are already using the latest version, please send a copy of your layout file so that I can debug this.

Haibao

**Comment by fantasticair** [comment]
Thank you for your rapid reply.
When I excute `python -m jcvi.graphics` command, the last line is `JCVI utility libraries v1.0.1 [Copyright (c) 2010-2019, Haibao Tang]`.

About my `layout` file as follows:
`# y, xstart, xend, rotation, color, label, va,  bed`
 `.6,     .1,    .7,       0,     green, Dglomerata, top, Dglomerata.bed`
 `.4,     .1,    .7,       0,     red, Athaliana, top, Athaliana.bed`
`# edges`
`e, 0, 1, Dglomerata.Athaliana.anchors.simple`

**Comment by tanghaibao** [comment]
@fantasticair 

Thank you for sending a sample layout file. This is a bug on my end (due to a recent change). The color assignment code was not working correctly (when colors were not specified, but should not have affected you).

I think I have fixed the issue and made a minor release. Try upgrading to `v1.0.2` (`pip install -U jcvi`) to see if this works now.

Haibao

**Comment by fantasticair** [comment]
Thanks to your upgrading. This bug was resolved.
