### ISSUE TITLE
how to set the opacity in microsynteny?

### ISSUE THREAD

**Issue by fangdm** [tanghaibao/jcvi#204]
Hi Dr. Tang, thanks for your excellent work at jcvi. 
I used this tool to show microsynteny between multi species, but I had no idea how to set the opacity of links and chromosome?
python -m jcvi.graphics.karyotype seqids layout

Thank you.

**Comment by tanghaibao** [comment]
@fangdm 

Currently the opacity (`alpha`) is set to a fixed value of 1 and is not yet configurable. However, they can both be easily reconfigured.

For links (shades), change `alpha=1` to any value between 0 (transparent) to 1 (opaque)

https://github.com/tanghaibao/jcvi/blob/0d813b4609330e36b3669706ac9d6bde3a4c919b/jcvi/graphics/karyotype.py#L294-L306

For chromosomes, `alpha=1` is not configured but need to be passed in:

https://github.com/tanghaibao/jcvi/blob/0d813b4609330e36b3669706ac9d6bde3a4c919b/jcvi/graphics/chromosome.py#L85-L100

The better solution is to allow configuration of `alpha` directly inside `layout` file. Please feel free to contribute - it may take me a while before I can get this in.

Haibao

**Comment by fangdm** [comment]
Thank you very much. 
I'm trying.

**Comment by tanghaibao** [comment]
@fangdm 

I just realized that you don't need to change any code to be able to set transparency.

Let's say your layout file looks like:

```
# y, xstart, xend, rotation, color, label, va,  bed
 .6,     .1,    .8,       0, #ff0000, Grape, top, grape.bed
 .4,     .1,    .8,       0, #00ff00, Peach, top, peach.bed
# edges
e, 0, 1, grape.peach.anchors.simple
```
Note that you can directly set transparency by adding another hex after the RGB, so called [RGBA](https://matplotlib.org/3.1.1/api/colors_api.html) (A is the `alpha`).

```
# y, xstart, xend, rotation, color, label, va,  bed
 .6,     .1,    .8,       0, #ff000080, Grape, top, grape.bed
 .4,     .1,    .8,       0, #00ff0080, Peach, top, peach.bed
# edges
e, 0, 1, grape.peach.anchors.simple
```

This is equivalent to setting `alpha=0.5`, since `0x80` in hex is equal to `128` which is half of the entire range between 0 to 255 (0xff).

Haibao
