### ISSUE TITLE
How to set the color of genes when we plot the microsynteny procedure?

### ISSUE THREAD

**Issue by awesomedeer** [tanghaibao/jcvi#217]
Hi Haibao
Jcvi is an amazing job!
I just find that the color of genes when I do microsynteny were green and blue . I want to give the gene their own color. I can't not find the parameters used to change colors neither. Any ideas about that? Do I need to change the code?
Thanks for your attention!

**Comment by tanghaibao** [comment]
@awesomedeer 

At this point, we do not expose the configuration of gene colors. This is the relevant code:

https://github.com/tanghaibao/jcvi/blob/c71a47fa3602905cdc8468ba1c011fe2028686fa/jcvi/graphics/synteny.py#L41

So forward genes are blue ('b') and backward genes are green ('g') and are currently fixed in the code. Just modify these two colors if you need.

Haibao

**Comment by awesomedeer** [comment]
Thanks. I also found that. Hope designating color to the genes is a new feature later. Really thanks for your efforts!
