### ISSUE TITLE
Can I use jcvi to plot the MCSCanX

### ISSUE THREAD

**Issue by wuxiaopei0509** [tanghaibao/jcvi#244]
Hi ,Mr Tang
I use MCSCanX to find collinearity blocks and found about 1000 blocks between two species ,However When I use the jcvi only 523 blocks in the Jcvi. My question is Can I use the MCScanX results to plot the  Synteny between the two species ?
Thank you

**Comment by tanghaibao** [comment]
@wuxiaopei0509 

The default filtering criteria (BLAST filters to remove weak and tandem duplicates) are different between MCScanX and jcvi version. The default synteny block threshold is also different. That's why the numbers are different. However, both should be fine to use as long as you keep track of the parameters that were used.

To plot MCscan results, you need to convert the MCScanX output to `.anchors` format. What is `.anchors` format? See [discussion](https://github.com/tanghaibao/jcvi/issues/141) here.

Haibao

**Comment by ShuaiNIEgithub** [comment]
Could you please show in code how to  convert the MCScanX output (.collinearity) to .anchors format?

**Comment by tanghaibao** [comment]
@ShuaiNIEgithub 

Sorry for the late response but you could try:

```console
python -m jcvi.compara.synteny fromaligns mc.collinearity
```

Let me know if this doesn't work and also send me a small file for testing.

**Comment by ShuaiNIEgithub** [comment]
@tanghaibao 
It worked and that's what I wanted. Thank you very much for your reply!

**Comment by mrmrwinter** [comment]
Hi @tanghaibao,
Rather than open a new issue i thought this was more appropriately posted here, as this is where my googling led me.

I wish to play with my macrosynteny plots in SynVisio.
Is there a way to convert an anchors file into a collinearity file?
Or would I have to install and runMCScanX to generate this?

Many thanks, really liking the software so far

**Comment by tanghaibao** [comment]
@mrmrwinter 

Unfortunately, we don't yet have a conversion script as you said at this point. If you do figure out how to do it, please consider contributing this. I think other ppl have asked about this in the past.

Haibao

**Comment by dengyang111** [comment]
> 
Hi mrmrwinter,
Have you solved this problem.
I also need to tansfer anchor files generated by JCVI to collinearity files generated by MCScanX, which could used by SynVisio.

**Comment by mpodio81** [comment]
I can not plot the synteny graph. The script gave me an error when I try to do it. It said that the chromosomes are empty. Could it be a problem with the seqid or layout files?
[outmcscan.err.txt](https://github.com/tanghaibao/jcvi/files/13229188/outmcscan.err.txt)
