### ISSUE TITLE
gff uniq drop CDS

### ISSUE THREAD

**Issue by lizihe21** [tanghaibao/jcvi#272]
Hi
I'm trying to filter dub gene in gff with jcvi.formats.gff uniq.But for each gene i will get only one CDS and the rest lost no matter i choose gene or mrna to uniq.How do i get full information for each gene?

**Comment by tanghaibao** [comment]
@lizihe21 

Thanks for reporting. Would you be able to send a small file for me to debug this issue?

**Comment by lizihe21** [comment]
Sure，i have sent an email to you

**Comment by tanghaibao** [comment]
@lizihe21 

Email sent. Add the response to this issue in case others may find this useful.

Thanks for sending a test file. The reason for retaining just a single CDS line is because they have the same ID. For example:

```console
chr29   Gnomon  CDS     371825  372013  .       -       0       ID=cds-XP_024843142.1;Parent=rna-XM_024987374.1;Dbxref=GeneID:789688,Genbank:XP_024843142.1;Name=XP
chr29   Gnomon  CDS     371422  371555  .       -       0       ID=cds-XP_024843142.1;Parent=rna-XM_024987374.1;Dbxref=GeneID:789688,Genbank:XP_024843142.1;Name=XP
chr29   Gnomon  CDS     371131  371280  .       -       1       ID=cds-XP_024843142.1;Parent=rna-XM_024987374.1;Dbxref=GeneID:789688,Genbank:XP_024843142.1;Name=XP
```

In this case, "uniq" just keeps the first one. Would you be able to make the CDS ids unique between different lines? Feel free to use the following commands:

```console
$ python -m jcvi.formats.gff format --unique chr29.gff > chr29.new.gff
```

Take a look at the diff between the newly generated file, you can see all the CDS IDs are now fixed, adding "-1", "-2" to differentiate between them.

```console
$ diff chr29.gff chr29.new.gff | less
```

Finally with the new GFF, you can re-redundify it:

```console
$ python -m jcvi.formats.gff uniq chr29.new.gff > chr29.uniq.gff
```

**Comment by lizihe21** [comment]
thanks a lot!
