### ISSUE TITLE
Questions about the names of chromosomes

### ISSUE THREAD

**Issue by Wangqq0515** [tanghaibao/jcvi#282]
Hello, thank you very much for your software has a great help to me, I have studied for a long time, help me decide a lot of things.I have a little question about why chromosome names are only shown numerically.For example: the name of chromosome is Chr1, and it is only shown as 1 in the figure. Can it be modified?

**Comment by tanghaibao** [comment]
@Wangqq0515 

This is the default behavior since the karyotype plot often has limited space to fit long chromosome names so it tries to truncate the name by using a number; otherwise, the plot may get too busy.

The extraction is implemented in the following method:

https://github.com/tanghaibao/jcvi/blob/ab9b1ffde9c07b39d0c0e0dbbc805ca5857704aa/jcvi/graphics/karyotype.py#L93-L119

Haibao
