### ISSUE TITLE
jcvi.graphics.chromosome : different colors randomly assigned to markers 

### ISSUE THREAD

**Issue by scotty323** [tanghaibao/jcvi#312]
[acoidmap.pdf](https://github.com/tanghaibao/jcvi/files/5473700/acoidmap.pdf)
Dear Prof. Tang,

I tried to map markers on multiple species chromosomes:

python -m jcvi.graphics.chromosome species.bed species.idmap --mergedist=1000000

But it always gives different colors for the same marker when I tried different times on different samples.

How can I fix the coler for the idmap file? So I can compare how the markers distributed in different samples.

Best,
Scotty

**Comment by tanghaibao** [comment]
@scotty323 

Current implementation randomly assigns colors. I'll leave this a TODO to see how I can fix this one.

**Comment by tanghaibao** [comment]
@scotty323 

I updated the code and also the bottom of the wiki (https://github.com/tanghaibao/jcvi/wiki/Miscellaneous-plotting) so that now you can specify column 3 with given colors and then the script will just use that color. Column 2 is still the feature legend label. Note that this `.idmap` file is **tab-separated**.

If you don't give this `.idmap` file, or that the `.idmap` file lacks column 3, colors will be randomly assigned as before. Please let me know if this helps to resolve your issue.

Haibao

**Comment by scotty323** [comment]
Dear Prof. Tang,

Thank you so much for modifying the code for us! You are a genius!

The IDMAP file with the 3rd column specifying the color works very nicely in the new verision JCVI!

It works!

Scotty

[acomarker.pdf](https://github.com/tanghaibao/jcvi/files/5492314/acomarker.pdf)

**Comment by tanghaibao** [comment]
Glad that I could be of help. If there's other issues related to this, feel free to open a ticket again.
