### ISSUE TITLE
Can't generate .bed file using MSTmap.out file

### ISSUE THREAD

**Issue by hungweichen0327** [tanghaibao/jcvi#317]
Dear community,

I have linkage map output file generated by MSTmap. When I used ``python -m jcvi.assembly.geneticmap`` to convert .out file to .bed file, I got the error.

The input file for python -m jcvi.assembly.geneticmap: 
[07-OUTPUT-CQ3649.txt](https://github.com/tanghaibao/jcvi/files/5587929/07-OUTPUT-CQ3649.txt)

The code I used is below:
```python -m jcvi.assembly.geneticmap bed 07-OUTPUT-CQ3649.out --switch```

The error message is in attachment.
[job_ALLMAPS_MSTMAP_file_convert_r2.txt](https://github.com/tanghaibao/jcvi/files/5587898/job_ALLMAPS_MSTMAP_file_convert_r2.txt)

Hope someone can help me find the problem. Thank you!

**Comment by tanghaibao** [comment]
@hungweichen0327 

Thanks for posting the issue. The error was due to your marker looking like `contig_25_pilon_pilon_pilon_30150000`, where the script expects to see `contig_25_pilon_pilon_pilon.30150000`. Note the delimiter that separates contig name and the position.

I have added option `--sep` to allow the use of characters other than ".". So now if you pull in the new changes, you can do:

```console
python -m jcvi.assembly.geneticmap bed 07-OUTPUT-CQ3649.txt --switch --sep _
```

Alternatively, if you can't or don't want to update the library, you can try to modify the marker names.

Haibao

**Comment by hungweichen0327** [comment]
Dear @tanghaibao,
Thank you for the quick reply. I tried the modified ``geneticmap.py`` and it worked!
