### ISSUE TITLE
How to add telomere points on chromsomes?

### ISSUE THREAD

**Issue by AlexWanghaoming** [tanghaibao/jcvi#339]
Dear developer,
If I want to add telomere points on chromosomes rectangle in karyotype plot, what source code do I need to modify in jcvi.graphics? I have the position file of each telomere on both right and left of my chromosomes.

**Comment by tanghaibao** [comment]
@AlexWanghaoming 

If it is in the karyotype plot then it is in this script:
https://github.com/tanghaibao/jcvi/blob/main/jcvi/graphics/karyotype.py

This is interesting since I always assume the telomeres are on the exact ends of the chromosomes? or do you mean centromere positions? Would it be possible to sketch what you want?

**Comment by AlexWanghaoming** [comment]
Thanks for your reply. Sometimes the assemblies are not in chromosome level and we would like to use syntenic plot to judge whether two contigs are generated from actual chromosome breakage or failed assembly. Therefore, we have located telomere position on all of contigs and  want to plot them on karyotype plot.

**Comment by YingChen94** [comment]
Hello, what command shall I use to add centromere positions onto the karyotype plot?
