### ISSUE TITLE
reciprocal microsynteny

### ISSUE THREAD

**Issue by cculma** [tanghaibao/jcvi#354]
Hi, I was creating a microsynteny analysis among a phased tetraploid genome. I have the four homologous chromosomes sequenced and I have the transcriptome data in aligned by chromosomes in a bed file. My goal is to identify genes which are present in one, two, three or four homologous chromosomes (named a, b, c and d). 

The command to generate the .anchors and .lifted.anchors files was:

`python -m jcvi.compara.catalog ortholog i_a i_b --cscore=.99 --no_strip_names`

[karyotype_chr6.pdf](https://github.com/tanghaibao/jcvi/files/5901031/karyotype_chr6.pdf)

However, when I was generating the microsynteny analysis, the list shared genes in all homologous chromosomes is not the same depending which  bed file I am using (`i_a.bed` or `i_b.bed`): 

`python -m jcvi.compara.synteny mcscan i_a.bed i_6a.i_6b.lifted.anchors --iter=1 -o i_a.i_b.i1.blocks
`
```
G2525;G2525.2   G5687;G5687.76
G2526;G2526.25  G5689;G5689.1
G2527;G2527.1   G5690;G5690.1
G2528;G2528.10  .
G2529;G2529.4   G5702;G5702.6
G2530;G2530.2   G5705;G5705.1
G2531;G2531.4   G5705;G5705.1
```

`python -m jcvi.compara.synteny mcscan i_b.bed i_a.i_b.lifted.anchors --iter=1 -o i_b.i_a.i1.blocks`

```
G5687;G5687.76  G2525;G2525.2
G5688;G5688.24  .
G5689;G5689.1   G2526;G2526.25
G5690;G5690.1   G2527;G2527.1
...
G5698;G5698.1   .
G5699;G5699.8   .
G5700;G5700.2   G2529;G2529.4
G5701;G5701.1   .
G5702;G5702.6   G2529;G2529.4
G5703;G5703.2   .
```

There is a problem with gene `G2529;G2529.4`, and I am obtaining different number of shared genes based on the way I compared the chromosomes. I would appreciate some advice to obtain the same number of homologous genes in all chromosomes.

Best,

Cesar

**Comment by tanghaibao** [comment]
@cculma 

This is to be expected. So what happens is that `G5700;G5700.2` and `G5702;G5702.6` are either proximal duplicate genes, or split genes (hard to know which at this point) - so they both match `G2529;G2529.4`. However, in the reverse direction, `G2529;G2529.4` picks `G5702;G5702.6` since that is the higher scoring match. This is biology.

I do not yet have a generally good method to give you 1-to-1 match. The same thing goes for BLAST, the results will be asymmetrical as well, depending on what you use for the query.

Just curious - what application do you have in mind that requires 1-to-1 (or consistent match)?

Haibao

**Comment by cculma** [comment]
Hi, I just want to identify the homologous genes present once, twice, three and four four times in homologous chromosomes in the phased genome. This is to relate the expression and homologous copies.  Thank you for your clarification.

Best,

Cesar
