### ISSUE TITLE
Will the synteny chromosome which only has two genes be filtered?  

### ISSUE THREAD

**Issue by 326reborn** [tanghaibao/jcvi#365]
Hi Haibao,
When I run "jcvi.compara.catalog ortholog" , I found my synteny chromosome with two genes existed in last.filtered but dispeared in .anchors. The synteny chromosome comes from the same specie. Is it because there are too few genes?

Thanks
Yu Zhang

**Comment by tanghaibao** [comment]
yes. The default synteny block size (`-n`) requires at least 4 genes.

**Comment by 326reborn** [comment]
Sorry, I didn't find this parameter(-n) in "jcvi.compara.catalog ortholog". 
Are there any parameters for adjusting the limits of synteny block size?

Thanks

**Comment by tanghaibao** [comment]
You can use `-n` to set a different value (for example, `-n 2`), but I don't recommend setting it to lower than 4 since that would just give you lots of blocks. btw if you just run the command with no arguments, it shows the help message, including a list of options that you can use.

```
$ python -m jcvi.compara.catalog ortholog
...
  -n N, --min_size=N    Minimum number of anchors in a cluster [default: 4]
```

The definition of synteny block is really a cluster of adjacent conserved genes. I don't think a block with two conserved genes makes much sense.

**Comment by tanghaibao** [comment]
As an extreme to consider, note that your entire collection of BLAST pairs are really synteny blocks with `-n 1`. As you use higher `n`, your results will include fewer pairs, but the blocks that you find are more likely to be stronger.

**Comment by 326reborn** [comment]
Thank you very much! It's helpful! May be I need to updata my jcvi.
It's right that a block with a few conserved genes barely makes much sense. However, there are some amazing organisms have the nanochromosome with a few conserved genes. It's fascinating to figure out how they got this way.

Best
Yu Zhang
