### ISSUE TITLE
Different result because of the order of the species

### ISSUE THREAD

**Issue by kedduck** [tanghaibao/jcvi#388]
Hello Professor Tang, first thanks for your efficient tools for syteny analysis.

Recently, I have a problem in analysing the microsynty between two species.

I find that different order will produce different results. For example :

specieA VS specieB (partial blocks)

![image](https://user-images.githubusercontent.com/37659948/126443852-5f2fa554-9db1-4bb9-9b13-eacaa5249f0a.png)

specieB VS specieA  (partial blocks)

![image](https://user-images.githubusercontent.com/37659948/126443981-6ed10e96-733e-4401-9f72-d094208bcd81.png)

It seems that the first column will not have repeat id and the microsynty result will be different.

Do you have some advice? 

Thanks for reading my question!

**Comment by tanghaibao** [comment]
@kedduck 

One gene match to multiple genes is often due to tandem/proximal duplications, or sometimes due to fused gene models.

This asymmetry is expected in the `.blocks` file. The `.anchors` is better in providing exhaustive list pairs.

If you are concerned about missing pairs in the microsynteny plot, you can manually append those pairs to the `.blocks` file (but flipping columns when you append them).

**Comment by kedduck** [comment]
Thanks for your detailed answer !
