### ISSUE TITLE
Buffer overflow with long filenames

### ISSUE THREAD

**Issue by erikvdbergh** [tanghaibao/jcvi#4]
Hi all,

Today I ran across a buffer overflow bug while using the ks app:
```
*** buffer overflow detected ***: /usr/local/bin/yn00 terminated
======= Backtrace: =========
*snip*
```

When I moved my folder to the home directory (resulting in a shorter absolute filename), everything worked fine. This is probably something in yn00 that is not taking in filenames properly. 

By testing, it seems that filenames longer than 95 characters are not accepted by yn00:
95 letters long:
```
yn00: /usr/local/bin/yn00 /home/vandene/AbcdefghijklmnopqrstuvwxyzAbcdefghijklmnopqrstuvwxyzAbc/syn_analysis/yn-input.ctl >/dev/null
Th2v09886;Th2v13841,4.0198,0.4937,-1.0000,0.4932
```
96 letter long:
```
yn00: /usr/local/bin/yn00 /home/vandene/AbcdefghijklmnopqrstuvwxyzAbcdefghijklmnopqrstuvwxyzAbcd/syn_analysis/yn-input.ctl >/dev/null
*** buffer overflow detected ***: /usr/local/bin/yn00 terminated
```

Perhaps a check to see if filename is longer than that and give a warning?

**Comment by vivekkrish** [comment]
Hi @erikvdbergh - Thank you for reporting this issue.

After taking a preliminary look at the code, it seems that the originator of this issue is the following line of code: [apps/ks.py#L476](https://github.com/tanghaibao/jcvi/blob/master/apps/ks.py#L476)
```
work_dir = op.join(os.getcwd(), "syn_analysis")
```
Basically, the computed `work_dir` parameter, which includes the full path to the current working directory, is propagated to the various compute steps:
* clustalw/muscle alignments [apps/ks.py#L492-L495](https://github.com/tanghaibao/jcvi/blob/master/apps/ks.py#L492-L495)
* mrtrans [apps/ks.py#L496](https://github.com/tanghaibao/jcvi/blob/master/apps/ks.py#L496)
* yn00 [apps/ks.py#L499](https://github.com/tanghaibao/jcvi/blob/master/apps/ks.py#L499)

Out of these 3 computational steps, it seems `yn00` is unable to handle a long path descriptor to the input control file.

Looking at the PAML yn00 implementation within BioPython, they also seem to try and avoid long paths by changing into the working directory first, before running the compute step: [Bio/Phylo/PAML/_paml.py#L135-L145](https://github.com/biopython/biopython/blob/master/Bio/Phylo/PAML/_paml.py#L135-L145)

I'm assuming that the simplest fix is to either construct a relative path to the control file (`./syn_analysis/yn-input.ctl`), or physically have the script change to the working directory before running the compute (like the BioPython implementation).

I'm going to wait for @tanghaibao to chime in as well, following which we can implement a quick fix.

Regards,
Vivek

**Comment by tanghaibao** [comment]
@erikvdbergh 

Thanks for exploring and reporting this issue. I think the fix is simply to remove the ``op.join`` part, as @vivekkrish suggested. I ran it on a small test case and the removal seems okay.

Haibao

**Comment by erikvdbergh** [comment]
Thanks Vivek and Haibao,

The new fix has resolved the issue, thanks for helping out.
