### ISSUE TITLE
Can the parameter --minsize not be set?

### ISSUE THREAD

**Issue by quxiaojian** [tanghaibao/jcvi#403]
Hi Haibao,
The default value of --minsize is 0. (I searched synteny.py from compara directory)
I want to know if we set --minspan=30, can --minsize not be set?

Thanks for your excellent tool.
Xiao-Jian Qu

**Comment by tanghaibao** [comment]
@quxiaojian 

`--minsize=0` is effectively NOT setting this parameter. Since synteny blocks would have non-zero (in fact, at least 4) anchors in them. Therefore, `--minsize=0` keeps all blocks without any filtering.

It is important to understand that `--minspan` is different from `--minsize`. 'Span' refers to how many genes between the left most anchor to the right most anchor). So `--minspan=30` means that there should be at least 30 genes between the first anchor and last anchor.

**Comment by quxiaojian** [comment]
Thanks!
