### ISSUE TITLE
e value filtering

### ISSUE THREAD

**Issue by fafuyyk** [tanghaibao/jcvi#418]
Dear Haibao,
    I want to know whether the low-quality anchors in the lifted.anchors file have low-quality evalue or lower than cscore; is the e-value filtered for the result of last during jcvi operation?
Thank you,
yyk

**Comment by tanghaibao** [comment]
@fafuyyk 

No these low-quality anchors (which have an `L` in the score column) are not filtered with E-value or C-score. That's why they are called low-quality.

They are only selected if both genes in the pair are within 10 genes apart from high-quality anchors, i.e. within the syntenic region.

**Comment by fafuyyk** [comment]
Hi Haibao,
Sorry, I still don't quite understand what you mean.

According to your statement, have the high-quality anchors been filtered by the e value? I checked the last file of jcvi and realized that these last files should not be filtered by the e value;

So I guess that the e value filter is built into the software. I want to know how many default parameters are related to the e value in the syteny analysis process and whether it can be adjusted.

Thank you
yyk

**Comment by tanghaibao** [comment]
@fafuyyk 

The high-quality anchors are all filtered by the C-value (by default, 0.7), which is a score relative to the best hit, and with tandem dups removed. This is the first step in the pipeline, and you can see the filtering results in `.last.filtered`.

There is NO filtering based on E-value in JCVI (except during one step in tandem dup filtering, where we require E-value to be less than 1e-10).

I find E-value less useful in synteny than C-value. First of all, the E-value definition is not very good since it changes when the database changes; Second, the E-value reported in LAST is not very accurate. LAST only reports the pair if they exceed some score, and never looks at its E-value (it only tries to compute an approximate E-value when the output format is BLAST-like). 

Therefore, in the JCVI pipeline, we just focus on the actual score, not the E-value. C-value is a much better method in my view to determine if a pair is weak.

**Comment by fafuyyk** [comment]
Thank you for your prompt reply
