### ISSUE TITLE
How to use MCScanX's result in jcvi?

### ISSUE THREAD

**Issue by phil622** [tanghaibao/jcvi#425]
First,thanks for this wonderful tool
This is my question:
I transform the .collinearity file from MCScanX to .anchor file use this command:

python -m jcvi.compara.synteny fromaligns mc.collinearity

But the .anchor file only get 2 column and not produce the score column, so i get this error in next step：

not enough values to unpack (expected 3, got 2)

How can i get the right .anchor file from .colinearity file ?

**Comment by annerilotter** [comment]
I have the same issue. Have you found a solution yet?

**Comment by somnya** [comment]
Hello, 

I did this and it worked:
tail -n+12  file.collinearity | sed -E 's/\##.+\s(Sc\w+)&(\w+)\s.+/#\1vs#\2/g' | sed -E 's/.+(Sc.+)\s(Sc.+)\t(.+)/\1\t\2\t0/g' > blocks.anchor
Still, I cannot realize how to get a bed file of syntenic blocks. I'd appreciate it if anyone could help.

Note: I replaced each e value to 0 since MCScan provides a scientific notation not supported by JCVI.

Tell me if it worked for you.
