### ISSUE TITLE
Disable Latex Plotting when using MCScan

### ISSUE THREAD

**Issue by obenno** [tanghaibao/jcvi#430]
Hi @tanghaibao,

May I ask is it possible to disable drawing dot plot via latex when running `python -m jcvi.compara.catalog ortholog` command? Thank you!

`jcvi` installed via **bioconda**:
- verion: `v1.1.19`
- build: `py39hcbe4a3b_0`

**Comment by tanghaibao** [comment]
@obenno 

May I ask is it because that the latex plotting fails for you? or you don't want to automatically draw the dot plot?

If it is the former, you can always re-generate the dot plot by running with `--notex`. 

```
python -m jcvi.graphics.dotplot X.Y.anchors --notex
```

Let me know if this works for you.

In the meantime, I have a potential fix that exposes `--notex` in the `ortholog` command but it might take a while before it shows up on bioconda.

**Comment by obenno** [comment]
@tanghaibao

Thanks for your quick response. I would like to integrate MCscan into our own pipeline, which may use other tools to draw the dot plot, thus we don't have to inlcude latex as the dependency. It would be nice if an option could be included to disable auto-drawing feature of `ortholog` command.

May I ask is `--notex` option use python's own ploting libarary?

**Comment by tanghaibao** [comment]
@obenno 

I see. I just added an option `--no_dotplot` and you can specify this in the `ortholog` command like this:

```
python -m jcvi.compara.catalog ortholog grape peach --no_strip_names --no_dotplot
```

It may take some time for `conda` to be able to upgrade to the latest. You can also use `pip install -U jcvi`.

**Comment by obenno** [comment]
@tanghaibao 

Thanks, it works like a charm!
