### ISSUE TITLE
The difference between rectangle and roundangle chromosome？

### ISSUE THREAD

**Issue by sunriseTM** [tanghaibao/jcvi#466]
Hi haibao，
    I am using jcvi to draw karyotype figure to reflex the microsynteny between chromosomes of specieses, but i am very confused about why some chromosomes  showed as rectangles and others showed as roundangles in one species genome , is there any biological meaning hidden? 
   And just as someone had asked before, if i want to add telomere on the ends of a chromosome in the figure, how shall i edit the scripts?
   Many thanks if you would be so kind to do me a favor!

Rui Wang from OUC

**Comment by tanghaibao** [comment]
@sunriseTM 

It was due to aesthetics. Some chromosomes are short. If they are shorter than a certain length, then they would be drawn as rectangles. Otherwise, they would look like circles, or even thin ovals, due to the fixed spaces used by the "rounded corners". 

I can add an option to make all chromosomes rectangles if you want. However, to make rounded corners on every chromosome including small ones, would not look pretty. If we add telomeres, then the length will no longer be accurately proportional.
