### ISSUE TITLE
Recycling of outputs

### ISSUE THREAD

**Issue by mrmrwinter** [tanghaibao/jcvi#503]
Hi, @tanghaibao, @Adamtaranto,

i noticed when running many iterations of the pipeline that sometimes files will be recycled and not regenerated even though different data was used as input. The main one is when running `jcvi.compara.catalog ortholog`, sometimes last will not generate a new alignment and will instead complete very quickly using the previously generated alignment. Ill gather more information on this when I can, and try to document a way to replicate the error.

**Comment by tanghaibao** [comment]
@mrmrwinter 

This is intentional. The files are checkpointed by timestamp. 
So if nothing is changed along the way then the pipeline will not regenerate the intermediate files or the final plot.

If you want to force the pipeline to re-run, then depending on what you need it to do, delete the corresponding intermediate files or the final plot.

**Comment by Adamtaranto** [comment]
Hi Haibao, 

We were thinking it would be useful to output an explicit warning whenever an intermediate file is detected and flagged for reuse. Is there a central class for handling checkpoints?

@mrmrwinter - Mike, when you were running iterations of the ortholog detection tool, were you seeing files recycled that should have been changed? i.e. after changing parameters or using new input contig sets.

**Comment by tanghaibao** [comment]
@Adamtaranto 

Good point. This should now log when the file is already up to date. Thanks for the suggestion.

**Comment by Adamtaranto** [comment]
@tanghaibao 

Thanks!
