### ISSUE TITLE
Can MCScan be used to detect orthologous gene?

### ISSUE THREAD

**Issue by gouwei1** [tanghaibao/jcvi#513]
Hi,

I was wanderring if MCScan can be used to detect orthologous gene. Compared with OrthoFinder, which one is more relieable?

Best,
Wei

**Comment by tanghaibao** [comment]
@gouwei1 

They serve different purposes. 

MCScan is to detect orthologs that have retained their chromosome positions (synteny) over evolutionary time. The synteny retention can be assumed only for closely related species since genomic shuffling tends to degrade synteny. Therefore, they are more appropriate for reasonably diverged species and can be more accurate than OrthoFinder for some genes (since the neighborhood is also used to infer orthology).

OrthoFinder is more generic and only requires sequence matches.

**Comment by gouwei1** [comment]
Thanks. Are the genes in *.lifted.anchors filtered by whether they are clustered into a block? The unclustered genes are removed?

**Comment by tanghaibao** [comment]
@gouwei1 

Yes, the pairs in the `.anchors` are syntenic gene pairs (high quality). `.lifted.anchors` is a more relaxed version (adding tandem gene duplicates back, as long as they are in the same neighborhood). 

Unclustered genes that do not have a syntenic match are removed from the anchors file.

**Comment by gouwei1** [comment]
That's good! Thank you for answering my questions.

Best regards,
Wei
