### ISSUE TITLE
Why chromosome ID is not displayed completely ？

### ISSUE THREAD

**Issue by guo-cheng** [tanghaibao/jcvi#532]
Hi Professor Tang,
When I use the MCScan to visualize the macrosynteny, the chromosome name is not displayed completely.
Please help me to solve this problem.

Best wishes!
Guo-Cheng
![xLXVL6](https://cdn.liguocheng.top//uPic/xLXVL6.png)

**Comment by tanghaibao** [comment]
@guo-cheng 

By default, the script will trim the chromosome name so that it is clearer, e.g. `1` vs `chromosome_1`. Sometimes, the trimming doesn't work well so it shows up blank.

https://github.com/tanghaibao/jcvi/blob/7c7844c7ba81c66e27549dfbabf29fac354faba8/jcvi/graphics/karyotype.py#L97

If you don't like the trimmed name, add an option `--keep-chrlabels`.

```console
python -m jcvi.graphics.karyotype seqids layout --keep-chrlabels
```
