### ISSUE TITLE
Help interpreting ALLMAPS dotplots

### ISSUE THREAD

**Issue by faye-romero** [tanghaibao/jcvi#562]
Hello @tanghaibao ,

I am struggling to interpret this output of ALLMAPS:
![Screen Shot 2023-04-28 at 2 29 12 PM](https://user-images.githubusercontent.com/101723465/235225615-cd93844a-d7db-4d44-89aa-71a3b06d46ad.png)

Does this just mean that, for Chr 15, the linkage map and the genome assembly were generated in reverse complement to each other (and therefore, these "inversions" are not meaningful)? Or is something more concerning going on? Should I question the quality of the linkage map and/or genome assembly?

Any help would be much appreciated.

**Comment by tanghaibao** [comment]
@faye-romero 

First of all, there is just a single contig of 15Mb in this case - and this becomes chr15 - ALLMAPS simply kept the single contig as is. This is shown on the right panel of the picture, there is just one contig (otherwise, the bottom chromosome will show multiple contigs with interleaving colors). In this case, no assembly actually happened and there is just one contig.

Now this single contig disagrees with the linkage map, by 2 inversions (this is different from just 1 inversion which can be explained by flipping the contig). Two inversions means that there is an error - the error is either from the genetic map, or from the contig. 

If we assume that the genetic map is correct, then the contig is chimeric and has to be split and re-assembled according to the genetic map.

Is it possible that the genetic map is wrong? Likely, but I wouldn't be able to evaluate from just the plot. It is also weird that there are zero markers in the first half of this linkage group.

In either case, this disagreement would require additional investigation.

**Comment by faye-romero** [comment]
@tanghaibao 

Thanks for your prompt reply! I will look into both the genetic map and the assembly.
