### ISSUE TITLE
why same gene can appear in different synteny block?

### ISSUE THREAD

**Issue by bucongfan** [tanghaibao/jcvi#593]
Hi Haibao,

I can understand that one gene can duplicate appearing in a block, which means some paralogous event,

But why can one gene appear in different block? How can I understand these results
>
![image](https://github.com/tanghaibao/jcvi/assets/51685446/a3660aa6-40c2-4249-b738-a8ea78c92dce)

**Comment by tanghaibao** [comment]
@bucongfan 

Two explanations:
- There are multiple genome duplications occurring in the past (this is actually quite common in plants, but also possible in vertebrates 2R/3R)
- One of these two blocks is an artifact of MCscan that just happen to cross threshold (the first block seems quite weak so it could be an artifact)

**Comment by bucongfan** [comment]
Thanks @tanghaibao ,

It seems that the second assumption might be more possible as its input was ecoli

The lifted results followed your guidance in wiki, how can I further filter weak blocks?

**Comment by tanghaibao** [comment]
@bucongfan 

Are these two different E.coli?

There are a couple of choices to make the block search more stringent. When you run:

```console
python -m jcvi.compara.catalog ortholog
...
  --cscore=CSCORE       C-score cutoff [default: 0.7]
  --dist=DIST           Extent of flanking regions to search [default: 20]
  -n N, --min_size=N    Minimum number of anchors in a cluster [default: 4]
  --quota=QUOTA         Quota align parameter [default: none]
```

If you like reciprocal best match, raise `--cscore 0.99`, or use `--min_size=20` to report synteny blocks of over 20 genes, or reduce `--dist=10` to chain synteny blocks to contain gap of no more than 10 genes, and finally also try using `--quota 1:1` to remove duplications (only 1:1 blocks).

Please note that since the results are cached, you may want to remove the generated `.anchors` file when you use a different set of parameters to filter.

**Comment by bucongfan** [comment]
Thank you @tanghaibao 

That quite helps me a lot!
