### ISSUE TITLE
Problems with .anchors file results

### ISSUE THREAD

**Issue by C-grapes** [tanghaibao/jcvi#595]
Dear Haibao!
Thank you for your excellent work on this tool. I have a few questions.
1, Why does a number like 283L appear in the third column of the .anchors file?  What does the L stand for?
2, I would like to use the synteny results to find the 100kb chromosome window that corresponds as closely as possible to the genomes of the two species in order to calculate whether the gene densities of the two genomes are correlated.  Is it possible to convert the coordinates based on the anchors file?  Should I choose the anchors file or .1x1.anchors?
  Best wish!

**Comment by tanghaibao** [comment]
@C-grapes 

1. `L` is an anchor that isn't part of the initial seed, but are lifted over. While they are still considered as anchors, they are of inferior quality compared to the non-`L` anchors in the same block.
2. You may need to find out the border of the synteny blocks based on the gene coordinates in the BED file and then process it. If you want to be sure about orthology between species, try `--cscore 0.99` in the initial run and choose the anchors file. You may not need the .1x1.anchors unless you have a situation where it is 1:2 or 1:3 (due to WGS) between the two species and you only want the best one.

**Comment by C-grapes** [comment]
> @C-grapes
> 
> 1. `L` is an anchor that isn't part of the initial seed, but are lifted over. While they are still considered as anchors, they are of inferior quality compared to the non-`L` anchors in the same block.
> 2. You may need to find out the border of the synteny blocks based on the gene coordinates in the BED file and then process it. If you want to be sure about orthology between species, try `--cscore 0.99` in the initial run and choose the anchors file. You may not need the .1x1.anchors unless you have a situation where it is 1:2 or 1:3 (due to WGS) between the two species and you only want the best one.

Thank you so much! You helped me a lot!
