### ISSUE TITLE
Can the number of genome duplication events be determined by highlighting the proportion of collinear gene blocks?

### ISSUE THREAD

**Issue by XXH123a** [tanghaibao/jcvi#642]
Dear Professor Tang,
![AB_colinearity](https://github.com/tanghaibao/jcvi/assets/96107726/a8a52199-919e-42ca-abb8-d24852fbcaad)
1. Species A has not undergone genome duplication, and using WGDI's own alignment, it is very certain that species B has undergone three whole genome duplications. The three red, green, and blue gene blocks in species A were randomly selected and all showed a 1:6 (-cscore=.99 --minspan=0) result. Is this proportional relationship reasonable given that it was caused by three duplications?
2. I am more confused about whether it is reasonable to have a ratio of 1:8 after three rounds of whole genome duplication, or whether it is due to gene loss and fusion, or due to filtering during alignment?
3, A small question, can I adjust the parameters so that only even numbers are displayed for the 29 chromosomes?
![29chr](https://github.com/tanghaibao/jcvi/assets/96107726/1ac0d0e6-52ce-4e8f-b6ff-18efadc31f2f)
Thank you for considering my question.

**Comment by tanghaibao** [comment]
@XXH123a 

1/2. Please send a dotplot (between A/B) since it's a lot easier to interpret with a dot plot. 1:6 is compatible with x2x3 event, or maybe as you said x2x2x2 but with gene loss (fractionation) or incomplete assembly

3. The step size is adjusted based on the number of chromosomes. Default behavior is to use step size of 2 when number of chromosomes is over `2 * MaxSeqids` (32). You can adjust `MaxSeqids` in the code to achieve that. Let me know if you need further help on this.
 https://github.com/tanghaibao/jcvi/blob/1092b219130256d5e0f26c3000a796d60ecf9862/jcvi/graphics/karyotype.py#L229-L233

**Comment by XXH123a** [comment]
Thank you very much for your reply. This is the dot plot of species A and B. the dot plot of multiple doubling events seems quite difficult for me.

**Comment by XXH123a** [comment]
Thank you very much for your reply. This is the dot plot of species A and B. the dot plot of multiple doubling events seems quite difficult for me.
![Uploading Am_Bs_dotplot.png…]()

**Comment by XXH123a** [comment]
![Am_Bs_dotplot](https://github.com/tanghaibao/jcvi/assets/96107726/7050ada6-43be-4115-95e6-b55d5255abd4)

**Comment by XXH123a** [comment]
I don't know whether you can see the dot map I uploaded. Sometimes the upload will fail. I tried the third question. It's more convenient to edit the chromosome ID manually ...
