### ISSUE TITLE
self-self synteny and colour based on cscore

### ISSUE THREAD

**Issue by MichelMoser** [tanghaibao/jcvi#73]
Hello Haibao, 

When doing self-self synteny plots, i get few gene-pairs. Is this because 1:1 hits with cscore = 1 in the plot get ignored? 
Or are they just represented by the purple diagonal line? 

[6maps_AXILLARIS_chr.6maps_AXILLARIS_chr.pdf](https://github.com/tanghaibao/jcvi/files/1305603/6maps_AXILLARIS_chr.6maps_AXILLARIS_chr.pdf)

Another question is the colouring of the dots. Is it possilbe to colour them according to cscores like it is done in CoGe synmap or MCscanX? 
In the options i find:
```
dotplot.py [anchorfile|ksfile] --qbed query.bed --sbed subject.bed

visualize the anchorfile in a dotplot. anchorfile contains two columns
indicating gene pairs, followed by an optional column (e.g. Ks value).
```
and my anchor file has a third column, but i dont think those are Ks values. 
I actually wonder what they are.

```
###
Peaxi162Scf01030g00013	Peaxi162Scf00026g02810	947
Peaxi162Scf01030g00012	Peaxi162Scf00026g00275	1430
Peaxi162Scf00541g00629	Peaxi162Scf00026g03012	767
Peaxi162Scf00541g00633	Peaxi162Scf00026g03111	1080

```
Can i calculate Ks values for genepairs with jcvi and add them as a column?

Thank you, 
Michel

**Comment by tanghaibao** [comment]
@MichelMoser 
For the first question, the pairs are fewer because: 1) AB pair is considered only as one pair, not two pairs; 2) self hits (or hits >98% similarity) are never counted since the usual use case for this is for screening of more ancient duplicates.

To plot the Ks values, append those values as the last column. Then use option ``--cmap_text=Ks`` , also play with options ``--vmin``, ``--vmax`` and ``--cmap`` to achieve the best visual effect.
