### ISSUE TITLE
Failure on syntelog data

### ISSUE THREAD

**Issue by tokurou** [tanghaibao/jcvi#74]
Hello, I am trying to generate a consensus sequence by combining three genetic maps and one cross-species synteny data. Applying the combined bed file from three genetic maps generated a consensus sequence successfully and it worked fine.
However, applying a bed file generated from the cross-species synteny data failed to work with a failure message KeyError: 'scaffold_xxx'.
A merged bed file combined with the synteny bed file and the genetic map data also failed to generate consensus sequence with a message 'AttributeError: 'ScaffoldOO' object has no attribute 'object''.
Because no error message appeared during conversion and data merge process, I think the file format of the synteny data would be correct.

Would you please suggest the points to be confirmed first?

Best,

**Comment by Jome0169** [comment]
Hello, 

Did you solve this error  Tokurou? I am having the exact same issue currently, and am unsure how to proceed.

Best,
Pablo

**Comment by ascendo** [comment]
Can you check the scaffold id in  cross-species synteny data ?

$ cat <bed file> | cut -f 1 | sort -u

**Comment by Jome0169** [comment]
These are the scaffold names from the bed file of the synteny data generated using the command 

> python -m jcvi.assembly.syntenypath bed chickpea.medicago.1x1.anchors --switch --scale=100000 -o Chickpea.bed

and then running your command above.

scaffold10
scaffold101
scaffold103
scaffold107
scaffold11
scaffold111
scaffold112
scaffold116
scaffold118
scaffold120
scaffold122
scaffold124
scaffold129
scaffold131
scaffold14
scaffold140
scaffold144
scaffold146
scaffold148
scaffold149
scaffold15
scaffold151
scaffold153
scaffold154
scaffold155
scaffold159
scaffold16
scaffold161
scaffold169
scaffold17
scaffold174
scaffold178
scaffold18
scaffold180
scaffold185
scaffold19
scaffold193
scaffold197
scaffold2
scaffold20
scaffold202
scaffold21
scaffold210
scaffold217
scaffold218
scaffold22
scaffold220
scaffold221
scaffold224
scaffold23
scaffold232
scaffold233
scaffold24
scaffold240
scaffold241
scaffold246
scaffold248
scaffold249
scaffold25
scaffold253
scaffold26
scaffold265
scaffold27
scaffold271
scaffold274
scaffold278
scaffold28
scaffold283
scaffold29
scaffold3
scaffold302
scaffold303
scaffold31
scaffold32
scaffold325
scaffold327
scaffold33
scaffold34
scaffold347
scaffold349
scaffold369
scaffold37
scaffold375
scaffold379
scaffold38
scaffold380
scaffold384
scaffold4
scaffold41
scaffold415
scaffold42
scaffold422
scaffold425
scaffold43
scaffold433
scaffold452
scaffold47
scaffold48
scaffold49
scaffold5
scaffold50
scaffold51
scaffold52
scaffold53
scaffold54
scaffold558
scaffold566
scaffold57
scaffold576
scaffold6
scaffold61
scaffold64
scaffold66
scaffold68
scaffold69
scaffold70
scaffold74
scaffold76
scaffold77
scaffold78
scaffold79
scaffold8
scaffold82
scaffold87
scaffold88
scaffold89
scaffold9
scaffold90
scaffold91
scaffold99

Strange because none of my scaffolds are named scaffold00. Any idea what the issue might be? If you can simply point me in the right direction I am sure I can figure the rest out

**Comment by ascendo** [comment]
show me your error first.

**Comment by Jome0169** [comment]
> $ python -m jcvi.assembly.allmaps path Final.bed MelonGenome.scf.fasta
14:34:12 [base] Load file `Final.bed`
14:34:12 [allmaps] Map contains 16739 markers in 13 linkage groups.
14:34:12 [allmaps] Retained 16,588 of 16,739 (99.1%) clean markers.
14:34:12 [base] Load file `weights.txt`
14:34:12 [base] Imported 2 records from `weights.txt`.
14:34:12 [allmaps] Map weights: [('syntenymap', 1), ('geneticmap', 1)]
14:34:12 [allmaps] Linkage function: double-linkage
14:34:12 [allmaps] Partition LGs based on geneticmap
14:34:13 [base] Load file `MelonGenome.scf.fasta.sizes`
14:34:13 [allmaps] Working on syntenymap-0|geneticmap-Citroides_Markers_Chrom_10-10|syntenymap-7|syntenymap-2|syntenymap-10 ...
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/data/pabster212/Programs/code/jcvi/assembly/allmaps.py", line 1871, in <module>
    main()
  File "/data/pabster212/Programs/code/jcvi/assembly/allmaps.py", line 827, in main
    p.dispatch(globals())
  File "/data/pabster212/Programs/code/jcvi/apps/base.py", line 96, in dispatch
    globals[action](sys.argv[2:])
  File "/data/pabster212/Programs/code/jcvi/assembly/allmaps.py", line 1484, in path
    ngen=ngen, npop=npop, cpus=cpus, seed=seed)
  File "/data/pabster212/Programs/code/jcvi/assembly/allmaps.py", line 151, in __init__
    print_tour(fwtour, self.object, tag, "INIT", tour, recode=True)
AttributeError: 'ScaffoldOO' object has no attribute 'object'

**Comment by ascendo** [comment]
$ egrep ScaffoldOO Final.bed

**Comment by Jome0169** [comment]
So, that's where this gets interesting, this returns nothing. I have searched all files I have used up to this point, and as far as I can tell this scaffold does not exist in my assembly

**Comment by ascendo** [comment]
yes I think so.

Beware when you use synteny, there are several species use only Scaffold## .

So I recommend to use scaffold## to species_scaffold##

**Comment by Jome0169** [comment]
Excellent, I will give this a shot! Thank you for the quick response

**Comment by ascendo** [comment]
use sed or vi

**Comment by Jome0169** [comment]
Hello,

The solution to the problem seems to be two-fold. One, I did rename all of my scaffolds to species_scaffold. I am not sure if this was the main issue as I was still getting the Scaffold00 error. 

The real issue seemed to be with the input bed file names. Whenever the bed files I input had a mix of characters in the title either '.' or '_' (eg.. Markers_Chrom_7.allmaps.rename.bed) I would get the **scaffold00 error**.

Once I renamed the input and output files to MarkersChrom7.bed, or something more simple the pipeline ran smoothly. 

Hope this helps someone in the future, and feel free to close this issue.

Best,
John Mendieta

**Comment by noschenk** [comment]
Hello,

I am experiencing the same/a similar error as tokurou and Jome0169, although I am working with optical mapping data (from Bionano) and a genetic map.
Jome0169's solution did not work for me, I removed all coocurrences of '_' and '.' from the file titles but I still get the 'Scaffold00' error.
My optical mapping scaffolds are named 'Super_Scaffold##' to avoid having the same names.
Like Jome0169, egrep Scaffold00 (or OO) did not find any occurrences in my input files.

when I run `python -m jcvi.assembly.allmaps path merged.bed scaffolds.fasta`, I get the following error message. (I copied out some lines so the message is not too long - and hopefully not too short):
```
13:48:48 [__init__] CACHEDIR=/home/exserta/.cache/matplotlib
13:48:48 [font_manager] Using fontManager instance from /home/exserta/.cache/matplotlib/fontList.json
13:48:48 [__init__] backend agg version v2.2
13:48:48 [base] Load file `merged.bed`
13:48:48 [allmaps] Map contains 1852 markers in 9 linkage groups.
13:48:48 [allmaps] Retained 1,707 of 1,852 (92.2%) clean markers.
13:48:48 [base] Load file `weights.txt`
13:48:48 [base] Imported 2 records from `weights.txt`.
13:48:48 [allmaps] Map weights: [('geneticmap', 1)]
13:48:48 [allmaps] Linkage function: double-linkage
13:48:48 [allmaps] Partition LGs based on geneticmap
...
13:48:48 [base] Load file `scaffolds.fasta.sizes`
13:48:48 [allmaps] Working on geneticmap-geneticmap-L.1 ...
Traceback (most recent call last):
  File "/home/exserta/anaconda2/envs/spassmitallmaps/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/exserta/anaconda2/envs/spassmitallmaps/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/exserta/anaconda2/envs/spassmitallmaps/lib/python2.7/site-packages/jcvi/assembly/allmaps.py", line 1871, in <module>
    main()
  File "/home/exserta/anaconda2/envs/spassmitallmaps/lib/python2.7/site-packages/jcvi/assembly/allmaps.py", line 827, in main
    p.dispatch(globals())
  File "/home/exserta/anaconda2/envs/spassmitallmaps/lib/python2.7/site-packages/jcvi/apps/base.py", line 96, in dispatch
    globals[action](sys.argv[2:])
  File "/home/exserta/anaconda2/envs/spassmitallmaps/lib/python2.7/site-packages/jcvi/assembly/allmaps.py", line 1484, in path
    ngen=ngen, npop=npop, cpus=cpus, seed=seed)
  File "/home/exserta/anaconda2/envs/spassmitallmaps/lib/python2.7/site-packages/jcvi/assembly/allmaps.py", line 151, in __init__
    print_tour(fwtour, self.object, tag, "INIT", tour, recode=True)
AttributeError: 'ScaffoldOO' object has no attribute 'object'
```

To give you some more information: I merged my genetic map and optical map together into `merged.bed` using the command `python -m jcvi.assembly.allmaps mergebed geneticmap.bed opticalmap.bed -o merged.bed`. The resulting `merged.bed` looks like:
Peex113Ctg00004	145	146	geneticmap-geneticmap-L.1:60.332313	Peex113Ctg00004:146	Peex113Ctg00004:146
Peex113Ctg00043	283	284	geneticmap-geneticmap-L.1:82.301015	Peex113Ctg00043:284	Peex113Ctg00043:284
Peex113Ctg00050	1266	1267	geneticmap-geneticmap-L.2:12.252585	Peex113Ctg00050:1267	Peex113Ctg00050:1267
Peex113Ctg00050	1267	1268	geneticmap-geneticmap-L.2:12.252585	Peex113Ctg00050:1268	Peex113Ctg00050:1268
Peex113Ctg00050	1268	1269	geneticmap-geneticmap-L.2:12.252585	Peex113Ctg00050:1269	Peex113Ctg00050:1269
Peex113Ctg00050	1269	1270	geneticmap-geneticmap-L.3:67.445686	Peex113Ctg00050:1270	Peex113Ctg00050:1270
Peex113Ctg00050	1697	1698	geneticmap-geneticmap-L.1:81.336551	Peex113Ctg00050:1698	Peex113Ctg00050:1698
Peex113Ctg00050	1698	1699	geneticmap-geneticmap-L.1:81.336551	Peex113Ctg00050:1699	Peex113Ctg00050:1699
Peex113Ctg00050	1699	1700	geneticmap-geneticmap-L.2:12.252585	Peex113Ctg00050:1700	Peex113Ctg00050:1700
...

I appreciate all hints, 
Best, Noelle

**Comment by yeban** [comment]
I had the same issue, but with genetic maps. The reason was similar to @Jome0169: entries in the 4th column of my BED file were in the format `m047-lg12:89.805000`. Removing the `m047-` part solved the issue.
